title: "&#FF9933Team Settings Panel"
size: 27
friendlyfire-slot: 10
teampay-slot: 11
echestlock-slot: 12
stats-slot: 13
joinpolicy-slot: 14
teamchat-slot: 15
invitepermission-slot: 16
loginalerts-slot: 19
requests-slot: 20
leave-slot: 21
disband-slot: 22
back-slot: 26
